version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    container_name: infraguard-backend

    ports:
      - "8000:8000"

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    container_name: infraguard-frontend

    ports:
      - "8501:8501"

    restart: unless-stopped

    environment:
      API_URL: http://backend:8000

    depends_on:
      - backend

  postgres:
    image: postgres:16

    container_name: infraguard-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: infraguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: