version: "3.9"

services:

  backend:
    build: .
    container_name: infraguard-backend

    ports:
      - "8000:8000"

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:16

    container_name: infraguard-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: infraguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: